# Generated by Django 3.1.3 on 2021-04-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarParks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parkName', models.CharField(max_length=30)),
                ('districtName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('openUntil', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='media/carparks')),
            ],
        ),
        migrations.DeleteModel(
            name='CarPark',
        ),
    ]
