# Generated by Django 3.1.3 on 2021-04-11 21:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carparks', '0002_auto_20210411_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='carparks',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 4, 11, 21, 46, 17, 686800, tzinfo=utc), editable=False, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
