# Generated by Django 3.1.3 on 2021-04-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carparks', '0003_carparks_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carparks',
            old_name='districtName',
            new_name='district_name',
        ),
        migrations.RenameField(
            model_name='carparks',
            old_name='openUntil',
            new_name='open_until',
        ),
        migrations.RenameField(
            model_name='carparks',
            old_name='parkName',
            new_name='park_name',
        ),
    ]
