# Generated by Django 3.1.3 on 2021-04-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carparks', '0005_auto_20210413_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carparks',
            name='slug',
        ),
    ]
