# Generated by Django 3.1.3 on 2021-04-13 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carparks', '0006_remove_carparks_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carparks',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, editable=False, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
